version: '3.8'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./BaseDatos/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: Blaziquen_01
      MYSQL_DATABASE: secretariadesalud
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  mensajeria:
    build:
      context: ./Mensajeria
    ports:
      - "1234:1234"
    depends_on:
      mysql:
        condition: service_healthy

  servidor:
    build:
      context: ./SecretariaSaludServer
    ports:
      - "12345:12345"
    depends_on:
      - mysql

  cliente:
    build:
      context: ./SecretariaSaludClient
    ports:
      - "8081:8080"
    depends_on:
      - servidor
    environment:
      SERVER_HOST: servidor
      SERVER_PORT: 12345

volumes:
  mysql_data:
