services:
  servidor-java:
    build:
      context: ./SecretariaSaludServer
    ports:
      - "80:80"
    depends_on:
      - base-de-datos

  servidor-web:
    build:
      context: ./SecretariaSaludClient
    ports:
      - "8081:8080"
    depends_on:
      - base-de-datos

  base-de-datos:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: AlexaSoto1
      MYSQL_DATABASE: secretariasalud

  servidor-rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
