version: '3.8'

services:
  mysql:
    build:
      context: ./BaseDatos
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mensajeria:
    build:
      context: ./Mensajeria
    ports:
      - "8083:8080"  # Cambiado el puerto de escucha para evitar conflicto con el servidor
    depends_on:
      - mysql

  servidor:
    build:
      context: ./SecretariaSaludServer
    ports:
      - "8082:8080"
    depends_on:
      - mensajeria

  cliente:
    build:
      context: ./SecretariaSaludClient
    ports:
      - "8081:8080"
    depends_on:
      - servidor

volumes:
  mysql_data:

